---
title: "DS202Lab2"
output: html_document
---

library(classdata)
data(choco)
str(choco)

#Question 1
```{r}
library(classdata)
data(choco)
str(choco)
hist(choco$CocoaPercent)
sort(choco$CocoaPercent)
tail(choco)
sort(choco$CocoaPercent, decreasing = TRUE)
# The histogram is not normally distributed, as it is slightly skewed left. It looks as though there may be outliers; however, we determined there are no outliers in this data, as there are values all of the way to 100, without any large breaks of having no values.
boxplot(choco$CocoaPercent)
#There are several outliers in the boxplot as many of the values fall outside of the interquartile range. In addition, the median of this data is around 70.
```
#Question 2
```{r}
counts<- table(choco$CountryBeanOrigin)
length(counts)
counts<-sort(counts, decreasing=TRUE)
counts<-head(counts,10)
barplot(counts, las=2, cex.names=0.6)
#The number of ratings differ based on the country of bean origin. For example, I took the top 10 countries with the highest number of ratings and created a bar plot to help me visualize the data more effectively. By referring to the graph below, you can see that Venezuela has the highest amount of ratings, which is omre than double the amount of ratings we see from the datasets countries with the 8, 9, and 10 highest ratings. 
```

#Question 3
```{r}
choco$group<-ifelse(choco$CocoaPercent > 70, 'high','low')
boxplot(choco$Rating ~ choco$group)
cor(choco$CocoaPercent, choco$Rating)
# Based on my graphical and numerical functions, I can determine that as the cocoa percentage increases in a chocolate bar, the rating of that chocolate bar decreases. This can be seen in the graph since the median rating of the high cocoa percentage is lower than the median rating of the low cocoa percentage group. In addition, from my numerical analysis, I have identified that there is a negative correlation between cocoa percentage and rating. Therefore, as the cocoa percentage increases, the rating decreases.
```

#Question 4
```{r}
table(choco$CountryBeanOrigin)
table(choco$SpecificBeanOrigin)

meanVenezuela <- mean(choco$Rating[choco$CountryBeanOrigin=='Venezuela'],na.rm=TRUE)
meanVenezuela
meanPeru<- mean(choco$Rating[choco$CountryBeanOrigin=='Peru'],na.rm=TRUE)
meanPeru
meanBrazil<- mean(choco$Rating[choco$CountryBeanOrigin=='Brazil'],na.rm=TRUE)
meanBrazil
barplot(c(meanVenezuela, meanPeru, meanBrazil),names.arg = c('Venezuela', 'Peru', 'Brazil'))
VenezuelaAVG<- mean(choco$Rating[choco$CountryBeanOrigin=='Venezuela'],na.rm=TRUE)
VenezuelaAVG
PeruAVG<-mean(choco$Rating[choco$CountryBeanOrigin=='Peru'],na.rm=TRUE)
PeruAVG
BrazilAVG<-mean(choco$Rating[choco$CountryBeanOrigin=='Brazil'],na.rm=TRUE)
BrazilAVG
#Based upon both my graphical and numerical analysis, I have determined that the flavor of chocolates from Venezuela, Peru, and Brazil do not differ significantly as their mean ratings are 3.22, 3.19, and 3.26, respectively. In the bar plot I created, each of the bars fall to a similar level. This then prompted me to identify what their actual means were from a numerical analysis. When doing so, I was able to identify a small range between the three of roughly .4.
```

#Question 5
```{r}
unique(choco$Company)
medianZotter <- median(choco$Rating[choco$Company=='Zotter'],na.rm=TRUE)
medianZotter
medianZokoko <- median(choco$Rating[choco$Company=='Zokoko'],na.rm=TRUE)
medianZokoko
medianWm <- mean(choco$Rating[choco$Company=='Wm'],na.rm=TRUE)
medianWm
barplot(c(medianZotter, medianZokoko, medianWm),names.arg = c('Zotter', 'Zokoko', 'Wm'))
#I first wanted to conduct an analysis to see which company, Zotter, Zokoko, or Wm had the best median flavor of chocolate based on their ratings. When looking at the bar plot I created, I you could easily identify that Zokoko has the best rating; however, it was a little more difficult to identify which company came in second. As a result, I then conducted a numerical analysis on Zotter, Zokoko, and Wm where I was able to identify their median ratings as 3.25, 3.5, and 3.4, respectively. As a result, I could determine that Zokoko had the best median flavor of chocolate, following by Wm having the second best median flavor, with Zotter have the worst median flavor of the three companies.

CPZotter <- median(choco$CocoaPercent[choco$Company=='Zotter'],na.rm=TRUE)
CPZotter
CPZokoko <- median(choco$CocoaPercent[choco$Company=='Zokoko'],na.rm=TRUE)
CPZokoko
CPWm <- median(choco$CocoaPercent[choco$Company=='Wm'],na.rm=TRUE)
CPWm
dat<-choco[choco$Company%in%c('Zotter','Zokoko','Wm'), ]
boxplot(dat$CocoaPercent ~ dat$Company)

#For this analysis, I wanted to detemine which of the three companies Zotter, Zokoko, or Wm used the most cocoa percentage in their chocolate based on  median. WHen doing so, I created a boxplot to help me visualize this, along with calculate our numercal data. From the boxplot, I could identify that Wm used the highest cocoa percentage, following by Zotter and Zokoko. The medians calculated from my numerical analysis for Wm, Zotter, and Zokoko were 74, 70, and 68, respectively.
```

#Push to Git
```{r}
git status